### ISSUE TITLE
Virus test run

### ISSUE THREAD

**Issue by SebastianZimmeck** [alpiazza13/Open-Source-Anti-Virus#24]
@kkkoech, @alpiazza13, @samueljaval, @jeremykattan, could you point me to an example file that your antivirus would flag as a virus? I tried the Single File Check option with some of your [testfiles](https://github.com/alpiazza13/Open-Source-Anti-Virus/tree/master/testfiles) (e.g., eicar.com), but none of the files were flagged as virus. I also tried a few from [theZoo](https://thezoo.morirt.com/), but no luck there either. Probably the ones I tested happen to be not yet in your list of viruses.

**Comment by ghost** [comment]
@SebastianZimmeck , thanks for the pointer! It could have been an issue with the version. Could you please download the [newer version](https://github.com/alpiazza13/Open-Source-Anti-Virus/raw/master/Anti-Virus(no_emoji).zip)?

**Comment by SebastianZimmeck** [comment]
Thanks, @kkkoech, for the newer version I am getting an error message "The application “main.app” can’t be opened. -47" when I am clicking on main.app.

**Comment by ghost** [comment]
@SebastianZimmeck , I think you're getting that because the app is from an "unidentified develeoper." On your mac, please go to "system preferences", then "security and privacy", and allow "main.app" to run on your computer. If this doesn't solve the problem, could you please attach a screenshot of the error?

**Comment by SebastianZimmeck** [comment]
Please see the screenshot attached (there is nothing additional under the question mark). The app is not asking for any permissions. I do not see anything in my "security and privacy" preferences. In the previous version I had indeed to give such confirmation, but not with this version.

<img width="417" alt="Screen Shot 2020-05-04 at 12 55 11 PM" src="https://user-images.githubusercontent.com/11034003/80991771-8628f300-8e06-11ea-84d6-53f06a03bc5f.png">

Is the error possibly due to the app being packaged under a different OS version that I am currently using (macOS Catalina 10.15.4)?

**Comment by samueljaval** [comment]
@SebastianZimmeck, I'm the one who packaged all the versions and I'm running macOS Mojave. But if one version worked for you at some point, then this can't be the problem because all the version have been packaged with the same OS.

**Comment by samueljaval** [comment]
You could also run the app by cloning the repo and running : python main.py

**Comment by samueljaval** [comment]
But it is important to us that the standalone app works, so it would be great if we could fix this issue that you are having.

**Comment by alpiazza13** [comment]
> Please see the screenshot attached (there is nothing additional under the question mark). The app is not asking for any permissions. I do not see anything in my "security and privacy" preferences. In the previous version I had indeed to give such confirmation, but not with this version.
> 
> <img alt="Screen Shot 2020-05-04 at 12 55 11 PM" width="417" src="https://user-images.githubusercontent.com/11034003/80991771-8628f300-8e06-11ea-84d6-53f06a03bc5f.png">
> 
> Is the error possibly due to the app being packaged under a different OS version that I am currently using (macOS Catalina 10.15.4)?

Also, when I test it (using the app itself or just by running main.py), all the files in testfiles/viruses are flagged as viruses. Hopefully this is the case for you as well but let us know if not!

**Comment by jeremykattan** [comment]
@SebastianZimmeck This is probably not the issue but try right clicking on the app icon and then pressing "open"

**Comment by SebastianZimmeck** [comment]
> But it is important to us that the standalone app works, so it would be great if we could fix this issue that you are having.

OK, I restarted my computer and ran the packaged app again. I received the warning below, allowed access, and it is working now. Not sure what the issue was.

<img width="415" alt="Screen Shot 2020-05-04 at 1 43 07 PM" src="https://user-images.githubusercontent.com/11034003/80996410-c344b380-8e0d-11ea-9589-76a7cac1b5ed.png">

> Also, when I test it (using the app itself or just by running main.py), all the files in testfiles/viruses are flagged as viruses. Hopefully this is the case for you as well but let us know if not!

Can you point me to a concrete file that should be flagged as a virus. I tried for example, virus1.txt and eicar_test_file.txt and those were not flagged.

**Comment by samueljaval** [comment]
@SebastianZimmeck virus1.txt should not be flagged as a virus because we were using it for old tests but it is not longer included in the virus list. On my computer, all the eicar files are flagged as viruses (as they should be) so I'm not sure why eicar_test_file.txt was not flagged for you

**Comment by samueljaval** [comment]
actually virus1.txt is also flagged as a virus for me, we probably just left it in the virus list

**Comment by alpiazza13** [comment]
> > But it is important to us that the standalone app works, so it would be great if we could fix this issue that you are having.
> 
> OK, I restarted my computer and ran the packaged app again. I received the warning below, allowed access, and it is working now. Not sure what the issue was.
> 
> <img alt="Screen Shot 2020-05-04 at 1 43 07 PM" width="415" src="https://user-images.githubusercontent.com/11034003/80996410-c344b380-8e0d-11ea-9589-76a7cac1b5ed.png">
> 
> > Also, when I test it (using the app itself or just by running main.py), all the files in testfiles/viruses are flagged as viruses. Hopefully this is the case for you as well but let us know if not!
> 
> Can you point me to a concrete file that should be flagged as a virus. I tried for example, virus1.txt and eicar_test_file.txt and those were not flagged.



> > But it is important to us that the standalone app works, so it would be great if we could fix this issue that you are having.
> 
> OK, I restarted my computer and ran the packaged app again. I received the warning below, allowed access, and it is working now. Not sure what the issue was.
> 
> <img alt="Screen Shot 2020-05-04 at 1 43 07 PM" width="415" src="https://user-images.githubusercontent.com/11034003/80996410-c344b380-8e0d-11ea-9589-76a7cac1b5ed.png">
> 
> > Also, when I test it (using the app itself or just by running main.py), all the files in testfiles/viruses are flagged as viruses. Hopefully this is the case for you as well but let us know if not!
> 
> Can you point me to a concrete file that should be flagged as a virus. I tried for example, virus1.txt and eicar_test_file.txt and those were not flagged.

yeah, like Sam said both of those files are flagged as viruses for me - as well as the two altered eicar files and virus3.txt. do you get the same results from running main.py ?

**Comment by SebastianZimmeck** [comment]
> yeah, like Sam said both of those files are flagged as viruses for me - as well as the two altered eicar files and virus3.txt. do you get the same results from running main.py ?

The result is still the same. I am using `python3 main.py` instead of `python main.py`, though. The latter does not seem to work. With the former, I am getting the following. 

There are a few "file not found" items, but that is really not the case. I am selecting the file, which exists, in the single file analysis dialog. 

Also, I am on a Quad-Core MacBook Pro. Not sure if this is related to the problem.

> Process Process-3:2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/is_virus.py", line 131, in is_virus_v2
    file_hex_str = get_hex_compressed(filefile, compress_bool=False)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/helpers.py", line 44, in get_hex_compressed
    file_bin = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/szimmeck/Downloads/eicar_test_file.txt'
Process Process-3:3:
Process Process-3:4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/is_virus.py", line 131, in is_virus_v2
    file_hex_str = get_hex_compressed(filefile, compress_bool=False)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/helpers.py", line 44, in get_hex_compressed
    file_bin = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/szimmeck/Downloads/eicar_test_file.txt'
Process Process-3:5:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/is_virus.py", line 131, in is_virus_v2
    file_hex_str = get_hex_compressed(filefile, compress_bool=False)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/helpers.py", line 44, in get_hex_compressed
    file_bin = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/szimmeck/Downloads/eicar_test_file.txt'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/is_virus.py", line 131, in is_virus_v2
    file_hex_str = get_hex_compressed(filefile, compress_bool=False)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/helpers.py", line 44, in get_hex_compressed
    file_bin = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/szimmeck/Downloads/eicar_test_file.txt'
Process Process-3:6:
Process Process-3:7:
Process Process-3:8:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/is_virus.py", line 131, in is_virus_v2
    file_hex_str = get_hex_compressed(filefile, compress_bool=False)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/helpers.py", line 44, in get_hex_compressed
    file_bin = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/szimmeck/Downloads/eicar_test_file.txt'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/is_virus.py", line 131, in is_virus_v2
    file_hex_str = get_hex_compressed(filefile, compress_bool=False)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/helpers.py", line 44, in get_hex_compressed
    file_bin = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/szimmeck/Downloads/eicar_test_file.txt'
Process Process-3:9:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/is_virus.py", line 131, in is_virus_v2
    file_hex_str = get_hex_compressed(filefile, compress_bool=False)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/helpers.py", line 44, in get_hex_compressed
    file_bin = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/szimmeck/Downloads/eicar_test_file.txt'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/is_virus.py", line 131, in is_virus_v2
    file_hex_str = get_hex_compressed(filefile, compress_bool=False)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/helpers.py", line 44, in get_hex_compressed
    file_bin = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/szimmeck/Downloads/eicar_test_file.txt'
Process Process-3:10:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/is_virus.py", line 131, in is_virus_v2
    file_hex_str = get_hex_compressed(filefile, compress_bool=False)
  File "/Users/szimmeck/Desktop/Code/Open-Source-Anti-Virus/helpers.py", line 44, in get_hex_compressed
    file_bin = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/szimmeck/Downloads/eicar_test_file.txt'
